myapp/urls.py
from myapp import views
from django.urls import path


app_name = "myapp"

urlpatterns = [
    path("", views.IndexView.as_view(), name="home"),
    path("introduction/", views.SelfIntroductionView.as_view(), name="introduction"),
    path("skill/", views.SkillView.as_view(), name="skill"),
    path("works/", views.WorkView.as_view(), name="works"),
    path("blog/", views.BlogView.as_view(), name="blog"),
    path("contact/", views.ContactView.as_view(), name="contact"),
    path("experience/", views.ExperienceView.as_view(), name="experience"),
    path("news/", views.NewsView.as_view(), name="news"),
]

myproject/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("myapp.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

tmpproject/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("myapp.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
# Create your models here.


class ImageModel(models.Model):
    background_image = models.ImageField(upload_to="img/upload", blank=True)
    description = models.TextField(
        max_length=200, default="Welcome to my site!!")
    profile_image = models.ImageField(upload_to="img/upload", blank=True)
    twitter = models.CharField(max_length=100, blank=True)
    github = models.CharField(max_length=100, blank=True)
    kaggle = models.CharField(max_length=100, blank=True)
    signate = models.CharField(max_length=100, blank=True)
    note = models.CharField(max_length=100, blank=True)


period_choice = (("一ヶ月程度", "一ヶ月程度"), ("二ヶ月から三ヶ月程", "二ヶ月から三ヶ月程"),
                 ("半年程", "半年程"), ("一年程", "一年程"), ("一年以上", "一年以上"))


class ContactModel(models.Model):
    email = models.EmailField(max_length=50, blank=True)
    twitter = models.CharField(max_length=100, blank=True)
    github = models.CharField(max_length=100, blank=True)
    kaggle = models.CharField(max_length=100, blank=True)


class SkillModel(models.Model):
    language = models.CharField(max_length=20, blank=True)
    period = models.CharField(
        max_length=20, blank=True, choices=period_choice)
    icon_name = models.CharField(max_length=20, blank=True)
    description = models.TextField(max_length=1000, blank=True)

    def __str__(self) -> str:
        return self.language


class IntroductionModel(models.Model):
    summary = models.TextField(max_length=300, blank=True)
    script = models.CharField(max_length=300, blank=True, null=True)
    name = models.TextField(max_length=200, blank=True)


class SelfIntroductionModel(models.Model):
    title = models.CharField(max_length=100, blank=True)
    description = models.TextField(
        max_length=10000, default="Please input text")

    def __str__(self) -> str:
        return self.title


class BlogModel(models.Model):
    title = models.CharField(max_length=100, blank=True)
    summary = models.TextField(max_length=300, blank=True)
    url = models.URLField(blank=True)
    script = models.TextField(max_length=10000, blank=True)

    def __str__(self) -> str:
        return self.title


class ExperienceModel(models.Model):
    summary = models.TextField(max_length=300, blank=True)
    url = models.URLField(blank=True)


class NewsModel(models.Model):
    news = models.TextField(max_length=200, blank=True)

myapp/views.py
from django.shortcuts import render
from django.views.generic import View
from .models import ImageModel, SkillModel, IntroductionModel, SelfIntroductionModel, BlogModel, ExperienceModel, ContactModel, NewsModel


class IndexView(View):
    """top page view"""

    def get(self, request, *args, **kwargs):
        introduction = IntroductionModel.objects.all()
        return render(request, "myapp/main.html", {"introduction_data":introduction})


class SelfIntroductionView(View):
    """top page view"""
    def get(self, request, *args, **kwargs):
        about_data = SelfIntroductionModel.objects.all()
        return render(request, "myapp/self_introduction.html", {"about_data":about_data})


class SkillView(View):
    """top page view"""
    def get(self, request, *args, **kwargs):
        skill_data = SkillModel.objects.all()
        return render(request, "myapp/skill.html", {"skill_data":skill_data})


class ContactView(View):
    """top page view"""
    def get(self, request, *args, **kwargs):
        contact_data = ContactModel.objects.all()
        return render(request, "myapp/contact.html", {"contact_data":contact_data})


class BlogView(View):
    """top page view"""
    def get(self, request, *args, **kwargs):
        blog_data = BlogModel.objects.all()
        return render(request, "myapp/blog.html", {"blog_data":blog_data})


class WorkView(View):
    """top page view"""
    def get(self, request, *args, **kwargs):
        skill_data = SkillModel.objects.all()
        return render(request, "myapp/works.html", {"skill_data":skill_data})


class ExperienceView(View):
    """top page view"""
    def get(self, request, *args, **kwargs):
        experience_data = ExperienceModel.objects.all()
        return render(request, "myapp/experience.html", {"experience_data":experience_data})


class NewsView(View):
    def get(self, request, *args, **kwargs):
        news_data = NewsModel.objects.all()
        return render(request, "myapp/news.html", {"news_data":news_data})

myapp/templates/myapp/blog.html
<!DOCTYPE html>
{% load static %}
{% comment %} {% load cloudinary %} {% endcomment %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static 'css/blog.css' %}">
        <title>Jukiyaのサイト</title>
        <div class="header">
            <div class="profile">
                <img src="/media/img/upload/my_favorite_photo.jpg" , alt="profile_icon" , width="150" , height="150">
                <h1><font color="black">Jukiya</font></h1>
            </div>
            <div class="page_link">
                <h3 id="introduction">自己紹介</h3>
                <h3 id="skill">スキル</h3>
                <h3 id="experience">今までやってきたこと</h3>
                <h3 id="works">作品</h3>
                <h3 id="blog">ブログ</h3>
                <h3 id="contact">連絡</h3>
                <h3 id="news">お知らせ</h3>
            </div>
        </div>
    </head>
    <body>
        <div class="title">
            <a href="{% url 'myapp:home' %}"><h3>HOME</h3></a>
            <h1 class="blog">ブログ紹介</h1>
        </div>
        <div class="blog_content", id="blogcontent">
            {% for blog in blog_data %}
            <ul>
                <li><a href="{{blog.url}}" ><h3>{{blog.title}}</h3></a></li>
                <li><p>{{ blog.summary | linebreaks }}</p></li>
            </ul>
            {% endfor %}
        </div>
    </body>
    <script src="{% static 'javascript/sideBar.js' %}"></script>
</html>

myapp/templates/myapp/contact.html
<!DOCTYPE html>
{% load static %}
{% comment %} {% load cloudinary %} {% endcomment %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static 'css/contact.css' %}">
        <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
        <title>Jukiyaのサイト</title>
        <div class="header">
            <div class="profile">
                <img src="/media/img/upload/my_favorite_photo.jpg" , alt="profile_icon" , width="150" , height="150">
                <h1><font color="black">Jukiya</font></h1>
            </div>
            <div class="page_link">
                <h3 id="introduction">自己紹介</h3>
                <h3 id="skill">スキル</h3>
                <h3 id="experience">今までやってきたこと</h3>
                <h3 id="works">作品</h3>
                <h3 id="blog">ブログ</h3>
                <h3 id="contact">連絡</h3>
                <h3 id="news">お知らせ</h3>
            </div>
        </div>
    </head>
    <body>
        <div class="title">
            <a href="{% url 'myapp:home' %}"><h3>HOME</h3></a>
            <h1 class="contact">連絡先</h1>
        </div>
        <div class="contact_content", id="contactacontent">
            {% for contact in contact_data %}
            <ul>
                <li><a class="twitter" href="{{contact.twitter}}" target="_blank">
                    <img src="/media/img/upload/twitter.svg">
                    <p>Twitter</p>
                </a></li>
                <li><a class="github" href="{{contact.github}}" target="_blank">
                    <img src="/media/img/upload/github.svg">
                    <p>Github</p>
                </a></li>
                <li><a class="kaggle" href="{{contact.kaggle}}" target="_blank">
                    <img src="/media/img/upload/kaggle.svg">
                    <p>kaggle</p>
                </a></li>
            {% endfor %}
        </div>
    </body>
    <script src="{% static 'javascript/sideBar.js' %}"></script>
</html>

myapp/templates/myapp/experience.html
<!DOCTYPE html>
{% load static %}
{% comment %} {% load cloudinary %} {% endcomment %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static 'css/experience.css' %}">
        <title>Jukiyaのサイト</title>
        <div class="header">
            <div class="profile">
                <img src="/media/img/upload/my_favorite_photo.jpg" , alt="profile_icon" , width="150" , height="150">
                <h1><font color="black">Jukiya</font></h1>
            </div>
            <div class="page_link">
                <h3 id="introduction">自己紹介</h3>
                <h3 id="skill">スキル</h3>
                <h3 id="experience">今までやってきたこと</h3>
                <h3 id="works">作品</h3>
                <h3 id="blog">ブログ</h3>
                <h3 id="contact">連絡</h3>
                <h3 id="news">お知らせ</h3>
            </div>
        </div>
    </head>
    <body>
        <div class="title">
            <a href="{% url 'myapp:home' %}"><h3>HOME</h3></a>
            <h1 class="experience">今までやってきたこと</h1>
        </div>
        <div class="experience_content", id="experiencecontent">
            {% for exp in experience_data %}
            <ul class="exp">
                <p>{{ exp.summary | linebreaks }}</p>
                {% if exp.url != ""%}
                <li><a href={{exp.url}} target="_blank">-> リンク</a><li>
                {%  endif %}
            </ul>
            {% endfor %}
        </div>
    </body>
    <script src="{% static 'javascript/sideBar.js' %}"></script>
</html>

myapp/templates/myapp/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <title>Jukiyaのサイト</title>
        <div class="header">
            <div class="profile">
                <img src="/media/img/upload/my_favorite_photo.jpg" alt="profile_icon" width="150" height="150">
                <h1 font color="black">Jukiya</h1>
            </div>
            <div class="page_link">
                <h3 id="introduction">自己紹介</h3>
                <h3 id="skill">スキル</h3>
                <h3 id="experience">今までやってきたこと</h3>
                <h3 id="works">作品</h3>
                <h3 id="blog">ブログ</h3>
                <h3 id="contact">連絡</h3>
                <h3 id="news">お知らせ</h3>
            </div>
        </div>
    </head>
    <body>
        <div class="title">
            <a href="{% url 'myapp:home' %}">
                <h3>HOME</h3>
            </a>
            <h1>ジュキヤのWebサイト</h1>
            <div class="news">
                <p>このサイトについて</p>
                <h5>現時点では最低限の機能しか実装していないので多少汚い部分があります。</h5>
                <h5>下のボタンから各ページに飛ぶことができますが、左のサイドバーからでも同様に動作します</h5>
                <h5>更新内容はお知らせのところに追加していきます。</h5>
            </div>
        </div>
        <ul class="main" style="list-style-type: disc">
            <div class="introduction_content" , id="aboutmecontent">
                {% for intro in introduction_data %}
                <li><p>{{ intro.summary | linebreaks }}</p></li>
                <li><Button id="{{intro.name}}">{{intro.name}}</Button></li>
                {% endfor %}
            </div>
        </ul>
    </body>
    <script src="{% static 'javascript/sideBar.js' %}"></script>
    <script src="{% static 'javascript/main.js' %}"></script>
</html>

myapp/templates/myapp/news.html
<!DOCTYPE html>
{% load static %}
{% comment %} {% load cloudinary %} {% endcomment %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static 'css/news.css' %}">
        <title>Jukiyaのサイト</title>
        <div class="header">
            <div class="profile">
                <img src="/media/img/upload/my_favorite_photo.jpg" , alt="profile_icon" , width="150" , height="150">
                <h1><font color="black">Jukiya</font></h1>
            </div>
            <div class="page_link">
                <h3 id="introduction">自己紹介</h3>
                <h3 id="skill">スキル</h3>
                <h3 id="experience">今までやってきたこと</h3>
                <h3 id="works">作品</h3>
                <h3 id="blog">ブログ</h3>
                <h3 id="contact">連絡</h3>
                <h3 id="news">お知らせ</h3>
            </div>
        </div>
    </head>

    <body>
        <div class="title">
            <a href="{% url 'myapp:home' %}"><h3>HOME</h3></a>
            <h1 class="news">お知らせ</h1>
        </div>
        <div class="news_content", id="newscontent">
            {% for news in news_data %}
            <ul>
                <li><h2>{{news.news | linebreaks}}</h2></li>
            </ul>
            {% endfor %}
        </div>
        <h1>Hello</h1>
    </body>
    <script src="{% static 'javascript/sideBar.js' %}"></script>
</html>

myapp/templates/myapp/self_introduction.html
<!DOCTYPE html>
{% load static %}
{% comment %} {% load cloudinary %} {% endcomment %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static 'css/introduction.css' %}">
        <title>Jukiyaのサイト</title>
        <div class="header">
            <div class="profile">
                <img src="/media/img/upload/my_favorite_photo.jpg" , alt="profile_icon" , width="150" , height="150">
                <h1><font color="black">Jukiya</font></h1>
            </div>
            <div class="page_link">
                <h3 id="introduction">自己紹介</h3>
                <h3 id="skill">スキル</h3>
                <h3 id="experience">今までやってきたこと</h3>
                <h3 id="works">作品</h3>
                <h3 id="blog">ブログ</h3>
                <h3 id="contact">連絡</h3>
                <h3 id="news">お知らせ</h3>
            </div>
        </div>
    </head>
    <body>
        <div class="title">
            <a href="{% url 'myapp:home' %}"><h3>HOME</h3></a>
        <h1 class="introduction">自己紹介</h1>
        </div>
        <div class="introduction_content", id="aboutmecontent">
            {% for about in about_data %}
            <ul>
                <li><h2>{{about.title}}</h2></li>
                <p>{{ about.description | linebreaks }}</p>
            </ul>
            {% endfor %}
        </div>
    </body>
    <script src="{% static 'javascript/sideBar.js' %}"></script>
</html>

myapp/templates/myapp/skill.html
<!DOCTYPE html>
{% load static %}
{% comment %} {% load cloudinary %} {% endcomment %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static 'css/skill.css' %}">
        <title>Jukiyaのサイト</title>
        <div class="header">
            <div class="profile">
                <img src="/media/img/upload/my_favorite_photo.jpg" , alt="profile_icon" , width="150" , height="150">
                <h1><font color="black">Jukiya</font></h1>
            </div>
            <div class="page_link">
                <h3 id="introduction">自己紹介</h3>
                <h3 id="skill">スキル</h3>
                <h3 id="experience">今までやってきたこと</h3>
                <h3 id="works">作品</h3>
                <h3 id="blog">ブログ</h3>
                <h3 id="contact">連絡</h3>
                <h3 id="news">お知らせ</h3>
            </div>
        </div>
    </head>
    <body>
        <div class="title">
            <a href="{% url 'myapp:home' %}"><h3>HOME</h3></a>
            <h1 class="skill">スキル紹介</h1>
        </div>
        <div id="Skill">
            <div class="skill_content">
                {%for skill in skill_data%}
                <div class="my_skill">
                    <img src="/media/img/upload/skill/{{skill.icon_name}}.svg" class="img_skill", alt="{{skill.icon_name}}">
                    <p class="language_name">{{skill.language}}</p>
                    <p class="period">{{skill.period}}</p>
                    <p class="description">{{skill.description | linebreaksbr}}</p>
                </div>
                {%endfor%}
    <script src="{% static 'javascript/sideBar.js' %}"></script>
</html>

myapp/templates/myapp/works.html
<!DOCTYPE html>
{% load static %}
{% comment %} {% load cloudinary %} {% endcomment %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static 'css/works.css' %}">
        <title>Jukiyaのサイト</title>
        <div class="header">
            <div class="profile">
                <img src="/media/img/upload/my_favorite_photo.jpg" , alt="profile_icon" , width="150" , height="150">
                <h1><font color="black">Jukiya</font></h1>
            </div>
            <div class="page_link">
                <h3 id="introduction">自己紹介</h3>
                <h3 id="skill">スキル</h3>
                <h3 id="experience">今までやってきたこと</h3>
                <h3 id="works">作品</h3>
                <h3 id="blog">ブログ</h3>
                <h3 id="contact">連絡</h3>
                <h3 id="news">お知らせ</h3>
            </div>
        </div>
    </head>
    <body>
        <div class="title">
            <a href="{% url 'myapp:home' %}"><h3>HOME</h3></a>
            <h1 class="works">作品紹介</h1>
        </div>
        <div class="work1">
            <h3>Typing RPG(予定)</h3>
            <p>完成予定: 2023/3月頃</p>
            <h3>使用技術</h3>
            <p>Unity C#</p>
            <video class="movie" controls width="600" height="600" src="/media/img/upload/TypingRPG_demo.mp4"></video>
    </body>
    <script src="{% static 'javascript/sideBar.js' %}"></script>
</html>